In [2]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec

In [3]:
DATA_IN_PATH = '../Embedding/embedding_data/'
model = Word2Vec.load(DATA_IN_PATH + 'Word2Vec_embedding.model').wv

In [4]:
label_data = pd.read_csv('../data/naverReview_label.csv')
label_data
# 라벨 데이터 199992개

label
0           0
1           1
2           0
3           0
4           1
...       ...
199987      1
199988      0
199989      0
199990      0
199991      0

[199992 rows x 1 columns]

In [5]:
train_data = pd.read_csv('../data/preprocess/naverReview_preprocess_Okt.csv', encoding = 'UTF8')
train_data
# 트레인 데이터 199992개

context
0                                        아 더빙 진짜 짜증나다 목소리
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다
2                                 너 무재 밓었 다그 래서 보다 추천 한 다
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...
...                                                   ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...
199991                                       마무리 는 또 왜 이래

[199992 rows x 1 columns]

In [6]:
train_data.dropna()
#dropna()로 NaN 제거 하니 198315 개

context
0                                        아 더빙 진짜 짜증나다 목소리
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다
2                                 너 무재 밓었 다그 래서 보다 추천 한 다
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...
...                                                   ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...
199991                                       마무리 는 또 왜 이래

[198315 rows x 1 columns]

In [7]:
new_data = pd.concat([train_data, label_data], axis=1)
new_data
#두개 다 같은걸 제거하기 위해 합치기

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[199992 rows x 2 columns]

In [8]:
new_data.dropna()

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[198315 rows x 2 columns]

In [9]:
new_data2 = new_data.dropna()

In [10]:
new_data2

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[198315 rows x 2 columns]

In [11]:
labels = list(new_data2['label'])
contexts = list(new_data2['context'])

sentences = []
for context in contexts :
    sentences.append(str(context).split())

In [12]:
def get_feature(words, model, num_features) :
    feature_vector = np.zeros((num_features), dtype = np.float32)
    
    num_words = 0
    index2word_set = set(model.wv.index2word)
    
    for w in words :
        if w in index2word_set :
            num_words += 1
            feature_vector = np.add(feature_vector, model[w])
    feature_vector = np.divide(feature_vector, num_words)
    return feature_vector

In [13]:
def get_dataset(reviews, model, num_features) :
    dataset = list()
    
    for s in reviews :
        dataset.append(get_feature(s, model, num_features))
        
    reviewFeatureVecs = np.stack(dataset)
    
    return reviewFeatureVecs

In [14]:
num_features = 100
test_data_vecs = get_dataset(sentences, model, num_features)

<ipython-input-12-c82fc869ee2a>:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  index2word_set = set(model.wv.index2word)
<ipython-input-12-c82fc869ee2a>:11: RuntimeWarning: invalid value encountered in true_divide
  feature_vector = np.divide(feature_vector, num_words)


In [24]:
test_data_vecs[28]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan], dtype=float32)

In [23]:
from sklearn.model_selection import train_test_split

X = np.array(contexts2)
y = np.array(labels2)

RANDOM_SEED = 42
TEST_SPLIT = 0.2

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SPLIT, random_state=RANDOM_SEED)

In [24]:
from sklearn.linear_model import LogisticRegression

lgs = LogisticRegression(class_weight='balanced')
lgs.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [25]:
print("훈련 데이터 정확도 : %f" % lgs.score(X_train, y_train))
print("테스트 데이터 정확도 : %f" % lgs.score(X_test, y_test))

훈련 데이터 정확도 : 0.823349
테스트 데이터 정확도 : 0.821096


In [26]:
import os
import re
from konlpy.tag import Okt
okt=Okt()

In [27]:
def preprocessing(review, okt, remove_stopwords = False):
    review_text = re.sub("[^가-힣ㄱ-ㅎㅏ-ㅣ\\s]", "", review)
    word_review = okt.morphs(review_text, stem = True)
    
    word_review = ' '.join(word_review)
    
    return word_review

In [28]:
def get_feature_predict(words, model, num_features) :
    feature_vector = np.zeros((num_features), dtype=np.float32)
    num_words = 0
    index2word_set = set(model.wv.index2word)
    for w in words.split() :
        if w in index2word_set :
            num_words += 1
            feature_vector = np.add(feature_vector, model.wv[w])
    feature_vector = np.divide(feature_vector, num_words)
    return feature_vector

In [29]:
def predict(review) :
    global model, num_features
    clean_review = preprocessing(review, okt, remove_stopwords=False)
    result = get_feature_predict(clean_review, model, num_features)
    List = []
    List.append(result)
    return lgs.predict(List)

In [45]:
predict("")

<ipython-input-28-f1669c899350>:4: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  index2word_set = set(model.wv.index2word)
<ipython-input-28-f1669c899350>:8: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  feature_vector = np.add(feature_vector, model.wv[w])


array([0])

In [37]:
test_data_vecs

array([[-0.35450596, -0.04077335,  0.28293362, ...,  0.00465774,
        -0.13556215,  0.1426918 ],
       [-0.2667003 ,  0.00871389, -0.00157211, ...,  0.11462455,
        -0.06821194,  0.17783464],
       [ 0.04544484, -0.00540596,  0.128162  , ...,  0.05045168,
        -0.0725171 ,  0.2765231 ],
       ...,
       [-0.20260756, -0.05997707,  0.03913534, ...,  0.03060072,
        -0.01594527,  0.09794391],
       [-0.10150812, -0.03976899,  0.03427497, ...,  0.07073486,
        -0.03985301,  0.13398297],
       [-0.14585307, -0.07677726, -0.07991358, ...,  0.24142866,
        -0.08730561, -0.01934249]], dtype=float32)

In [41]:
type(test_data)

list

In [15]:
test_data = test_data_vecs.tolist()

In [15]:
test_data

[[-0.3545059561729431,
  -0.04077335447072983,
  0.28293362259864807,
  0.08119475841522217,
  0.013993864879012108,
  -0.23043903708457947,
  0.1440812051296234,
  -0.03161213546991348,
  -0.2930770218372345,
  -0.11646007001399994,
  0.08782942593097687,
  -0.028571540489792824,
  -0.009507880546152592,
  -0.20840802788734436,
  0.1334509253501892,
  -0.07679030299186707,
  0.26739501953125,
  -0.09764659404754639,
  -0.277314156293869,
  0.4097803235054016,
  -0.07486739754676819,
  0.01392635703086853,
  0.1293705403804779,
  -0.01340187806636095,
  -0.24470433592796326,
  -0.17701201140880585,
  -0.36821097135543823,
  -0.06285887211561203,
  -0.25019603967666626,
  -0.358634889125824,
  0.06940057128667831,
  0.25392064452171326,
  -0.37718576192855835,
  0.16960403323173523,
  -0.06376682221889496,
  -0.3005886971950531,
  -0.03963961452245712,
  0.36043065786361694,
  -0.44711700081825256,
  0.1200757771730423,
  0.03941255062818527,
  0.23736515641212463,
  0.14915499091148376

In [16]:
test_data_df = pd.DataFrame({'context' : test_data})

In [45]:
test_data_df

context
0       [-0.3545059561729431, -0.04077335447072983, 0....
1       [-0.26670029759407043, 0.008713889867067337, -...
2       [0.04544483870267868, -0.005405960604548454, 0...
3       [-0.24363183975219727, -0.09286148101091385, 0...
4       [-0.07732874900102615, -0.03550983592867851, -...
...                                                   ...
198310  [-0.0050431666895747185, -0.032580893486738205...
198311  [-0.16151383519172668, -0.004260162357240915, ...
198312  [-0.20260755717754364, -0.05997707322239876, 0...
198313  [-0.10150811821222305, -0.03976898640394211, 0...
198314  [-0.14585307240486145, -0.07677726447582245, -...

[198315 rows x 1 columns]

In [17]:
label_df = pd.DataFrame({'label': labels})

In [50]:
label_df

label
0           0
1           1
2           0
3           0
4           1
...       ...
198310      1
198311      0
198312      0
198313      0
198314      0

[198315 rows x 1 columns]

In [18]:
new_df = pd.concat([test_data_df, label_df], axis=1)

In [19]:
new_df.index = range(198315)

In [20]:
nan_index = []
for index in range(198315) :
    npArray = np.asarray(new_df['context'].iloc[index], dtype=np.float32)
    if np.isnan(npArray).any() :
        nan_index.append(index)
        
print(nan_index)

[28, 79, 169, 414, 1150, 1349, 1575, 1715, 2328, 2352, 2440, 3451, 4307, 4830, 5043, 5748, 7187, 7839, 8395, 9407, 9726, 10678, 11061, 11764, 12829, 12875, 13011, 13646, 13788, 15579, 15838, 16952, 18795, 18824, 19493, 20631, 21531, 23298, 24865, 25154, 25315, 26152, 26610, 27432, 27830, 28819, 28946, 29290, 29991, 30575, 31020, 31330, 32639, 33140, 33310, 33322, 34482, 34686, 35400, 36802, 37622, 38009, 40223, 40593, 40957, 41267, 43869, 44074, 44510, 44768, 45315, 45495, 46047, 46089, 46840, 47074, 47514, 47636, 48189, 48605, 49583, 49615, 49736, 50449, 50785, 51902, 52871, 53624, 53829, 54425, 54956, 55527, 55768, 56424, 57196, 57906, 57975, 58342, 59817, 61460, 61744, 62836, 63006, 63169, 63668, 64173, 64581, 64733, 65351, 65453, 66323, 66634, 67217, 67848, 68139, 68902, 69137, 69261, 70715, 71386, 71767, 72591, 73434, 74589, 75081, 75166, 75362, 75542, 76910, 77324, 78809, 78856, 79189, 79482, 79881, 80651, 81253, 81485, 82068, 82181, 83389, 84432, 86131, 86614, 88291, 88347, 8897

In [21]:
new_df2 = new_df.drop(nan_index)
new_df2

context  label
0       [-0.3545059561729431, -0.04077335447072983, 0....      0
1       [-0.26670029759407043, 0.008713889867067337, -...      1
2       [0.04544483870267868, -0.005405960604548454, 0...      0
3       [-0.24363183975219727, -0.09286148101091385, 0...      0
4       [-0.07732874900102615, -0.03550983592867851, -...      1
...                                                   ...    ...
198310  [-0.0050431666895747185, -0.032580893486738205...      1
198311  [-0.16151383519172668, -0.004260162357240915, ...      0
198312  [-0.20260755717754364, -0.05997707322239876, 0...      0
198313  [-0.10150811821222305, -0.03976898640394211, 0...      0
198314  [-0.14585307240486145, -0.07677726447582245, -...      0

[197954 rows x 2 columns]

In [44]:
len(nan_index) + 198315 

198676

In [22]:
labels2 = list(new_df2['label'])
contexts2 = list(new_df2['context'])