In [1]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec

In [2]:
DATA_IN_PATH = '../Embedding/embedding_data/'
model = Word2Vec.load(DATA_IN_PATH + 'Word2Vec_embedding.model').wv

In [3]:
label_data = pd.read_csv('../data/naverReview_label.csv')
label_data
# 라벨 데이터 199992개

label
0           0
1           1
2           0
3           0
4           1
...       ...
199987      1
199988      0
199989      0
199990      0
199991      0

[199992 rows x 1 columns]

In [49]:
train_data.head(30)

context
0                                    아 더빙 진짜 짜증나다 목소리
1                    흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다
2                             너 무재 밓었 다그 래서 보다 추천 한 다
3                       교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정
4   사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...
5    막 걸음 마 떼다 세 부터 초등학교 학년 생인 살다 영화 ㅋㅋㅋ 별 반개 도 아깝다 움
6                               원작 의 긴장감 을 제대로 살리다 하다
7   별 반개 도 아깝다 욕 나오다 이응경 길용우 연 기 생활 이 몇 년 인지 정말 발 ...
8                              액션 이 없다 재미 있다 몇 안되다 영화
9         왜케 평점 이 낮다 꽤 볼 만 한 데 헐리우드 식 화려하다 너무 길들이다 있다
10                              걍 인피니트 가 짱 이다 진짜 짱 이다
11   볼때 마다 눈물나다 죽다 년대 의 향수 자 극 허진호 는 감성 절제 멜로 의 달인 이다
12    울면 서 손 들 고 횡단보도 건너다 때 뛰다 치다 올 뻔 이범수 연기 드럽다 못 하다
13  담백하다 깔끔하다 좋다 신 문 기 사 로만 보다 보다 자꾸 잊어버리다 그 들 도 사...
14  취향 은 존중 한 다지 만 진짜 내생 에 극장 에서 보다 영화 중 가장 노잼 노 감...
15                                ㄱ 냥 매번 긴장 되다 재밋음 ㅠㅠ
16  차다 사람 들 웃기다 바스코 가 이기 면 락스 코 라고 끄다 바비 가 이기 면 아이...
17            굿바이 레닌 표절 인 것 은 이해 하다 왜 뒤 로 갈수록 재미 없어지다
18  이건 정말 깨알 캐스팅 과 질퍽 하 지 않다 산뜻하다 내 용구성 이 자다 버무러진 ...
19       약탈 자 를 위 한 변명 이르다 저 놈 들 은 착하다 놈 들 절대 아니다 걸 요
20       나름 심오하다 뜻 도 있다 듯 그냥 학생 이 선생 과 놀다 영화 는 절대 아니다
21                                   보다 웃다 않다 건 불가능하다
22  재미없다 지루하다 같다 음식 영화 인데 도 바베트 의 만찬 하고 넘다 차이 남바 베...
23                    절대 평범하다 영화 가 아니다 수작 이라 는걸 말씀드리다
24                                 주제 는 좋다 중반 부터 지루하다
25               다 짤랐을꺼 야 그래서 납득 하다 수 없다 그렇다 꼭 그렇다 끄다
26                                     고추 를 털다 버리다 하다
27                                          카밀라 벨 발연기
28                                               재밋는뎅
29                  센스 있다 연출 력 탁월하다 캐스팅 년대 의 향수 그래서 점

In [4]:
train_data = pd.read_csv('../data/preprocess/naverReview_preprocess_Okt.csv', encoding = 'UTF8')
train_data
# 트레인 데이터 199992개

context
0                                        아 더빙 진짜 짜증나다 목소리
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다
2                                 너 무재 밓었 다그 래서 보다 추천 한 다
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...
...                                                   ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...
199991                                       마무리 는 또 왜 이래

[199992 rows x 1 columns]

In [5]:
train_data.dropna()
#dropna()로 NaN 제거 하니 198315 개

context
0                                        아 더빙 진짜 짜증나다 목소리
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다
2                                 너 무재 밓었 다그 래서 보다 추천 한 다
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...
...                                                   ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...
199991                                       마무리 는 또 왜 이래

[198315 rows x 1 columns]

In [6]:
new_data = pd.concat([train_data, label_data], axis=1)
new_data
#두개 다 같은걸 제거하기 위해 합치기

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[199992 rows x 2 columns]

In [7]:
new_data.dropna()

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[198315 rows x 2 columns]

In [8]:
new_data2 = new_data.dropna()

In [9]:
new_data2

context  label
0                                        아 더빙 진짜 짜증나다 목소리      0
1                        흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다      1
2                                 너 무재 밓었 다그 래서 보다 추천 한 다      0
3                           교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정      0
4       사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하...      1
...                                                   ...    ...
199987   오랜 만 에 평점 로 기다 하다 ㅋㅋ 킹왕짱 쌈뽕 한 영화 를 만나다 강렬하다 육 쾌함      1
199988         의지 박약 들 이나 하다 탈영 은 일단 주인공 김대희 닮다 이등병 찌다 따다      0
199989                    그림 도 좋다 완성 도도 높다 보다 내내 불안하다 만들다      0
199990  절대 보다 서다 안 되다 영화 재미 도 없다 기분 만 잡 치고 하다 세트 장 에서 ...      0
199991                                       마무리 는 또 왜 이래      0

[198315 rows x 2 columns]

In [10]:
labels = list(new_data2['label'])
contexts = list(new_data2['context'])

sentences = []
for context in contexts :
    sentences.append(str(context).split())

In [11]:
print(contexts[0])

아 더빙 진짜 짜증나다 목소리


In [58]:
def get_feature(words, model, num_features) :
    feature_vector = np.zeros((num_features), dtype = np.float32)
    
    num_words = 0
    index2word_set = set(model.wv.index2word)
    
    for w in words :
        if w in index2word_set :
            num_words += 1
            feature_vector = np.add(feature_vector, model[w])
            
    feature_vector = np.divide(feature_vector, num_words)
    if num_words == 0 :
        return np.zeros((num_features), dtype = np.float32)
    return feature_vector

In [59]:
def get_dataset(reviews, model, num_features) :
    dataset = list()
    
    for s in reviews :
        dataset.append(get_feature(s, model, num_features))
        
    reviewFeatureVecs = np.stack(dataset)
    
    return reviewFeatureVecs

In [60]:
test_data_vecs = get_dataset(sentences, model, 100)

C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [29]:
for i in range(10, 100) :
    print(test_data_vecs[i], i)

[ 0.0144924   0.0634408   0.09300235  0.21882424  0.00041076 -0.39354482
  0.19349416 -0.0967304  -0.12375423  0.00811052  0.2553967  -0.07079649
  0.05383144  0.01760668  0.08840902  0.10443485  0.01860933 -0.01862409
 -0.07219261  0.29765195 -0.01913707  0.30335674  0.10418755 -0.13247897
 -0.294957   -0.10225796 -0.28585517 -0.16056494  0.13729532 -0.24035838
 -0.05868956  0.13657749 -0.05616669  0.17026892 -0.18964316 -0.28870773
  0.09393553  0.24182574 -0.3373392   0.28471485  0.28427172  0.1969542
  0.07792911 -0.2867731   0.22441313  0.20107481  0.2534793  -0.38501856
 -0.11116956  0.2478953  -0.23234828 -0.16557974  0.02241898 -0.24609141
  0.06797755  0.20151621  0.3098213   0.07030761 -0.11126968  0.05764975
  0.20166433 -0.25327814  0.10806492  0.24355225 -0.30692613  0.05788619
 -0.05120542 -0.34176552 -0.00571904  0.3387701  -0.02396719  0.04434985
 -0.10325371  0.01158969  0.17064382 -0.19891872  0.17673075 -0.10624865
 -0.05341634 -0.07399547 -0.278414   -0.07416229 -0.

In [134]:
print(get_feature(sentences[28], model, 100))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [61]:
from sklearn.model_selection import train_test_split

X = test_data_vecs
y = np.array(labels)

RANDOM_SEED = 42
TEST_SPLIT = 0.2

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SPLIT, random_state=RANDOM_SEED)

In [62]:
from sklearn.linear_model import LogisticRegression

lgs = LogisticRegression(class_weight='balanced')
lgs.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [64]:
print("훈련 데이터 정확도 : %f" % lgs.score(X_train, y_train))
print("테스트 데이터 정확도 : %f" % lgs.score(X_test, y_test))

훈련 데이터 정확도 : 0.821433
테스트 데이터 정확도 : 0.823160


In [139]:
from konlpy.tag import Okt

okt = Okt()

def preprocessing(review, okt, remove_stopwords = False):
    review_text = re.sub("[^가-힣ㄱ-ㅎㅏ-ㅣ\\s]", "", review)
    word_review = okt.morphs(review_text, stem = True)
    
    word_review = ' '.join(word_review)
    return word_review

In [145]:
def get_feature_predict(words, model, num_features) :
    feature_vector = np.zeros((num_features), dtype=np.float32)
    
    num_words = 0
    index2word_set = set(model.wv.index2word)
    for w in words.split() :
        if w in index2word_set :
            num_words += 1
            feature_vector = np.add(feature_vector, model.wv[w])
            
    feature_vector = np.divide(feature_vector, num_words)
    return feature_vector

In [146]:
def predict(review) :
    global model, num_features
    clean_review = preprocessing(review, okt, remove_stopwords=False)
    result = get_feature_predict(clean_review, model, 100)
    List = []
    List.append(result)
    return lgs.predict(List)

In [147]:
from bs4 import BeautifulSoup
import re

In [148]:
predict("이 영화 재밌네요")

C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


array([1])

In [149]:
predict("재밌겠당")

C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


array([1])

In [150]:
predict("다신 안본다")

C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """
C:\Users\korea_1\anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  if __name__ == '__main__':


array([0])

In [153]:
print(preprocessing("재밋는뎅", okt))

재밋는뎅
